//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Website.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.DetailBills = new HashSet<DetailBill>();
            this.Detailimportcoupons = new HashSet<Detailimportcoupon>();
        }
    
        public string ProductID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string ProductName { get; set; }
        public string Unit { get; set; }
        public string Photo { get; set; }
        public int Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<DetailBill> DetailBills { get; set; }
        public virtual ICollection<Detailimportcoupon> Detailimportcoupons { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
