//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Website.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detailimportcoupon
    {
        public int DetailimportID { get; set; }
        public Nullable<int> ImportID { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Price { get; set; }
        public string Location { get; set; }
        public string ProductID { get; set; }
    
        public virtual Importcoupon Importcoupon { get; set; }
        public virtual Product Product { get; set; }
    }
}
