//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Website.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKEntities : DbContext
    {
        public QLKEntities()
            : base("name=QLKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<DetailBill> DetailBills { get; set; }
        public virtual DbSet<Detailimportcoupon> Detailimportcoupons { get; set; }
        public virtual DbSet<Importcoupon> Importcoupons { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SystemDatabase> SystemDatabases { get; set; }
        public virtual DbSet<Uploadfile> Uploadfiles { get; set; }
        public virtual DbSet<UploadPhotoBill> UploadPhotoBills { get; set; }
        public virtual DbSet<UploadPhotoProduct> UploadPhotoProducts { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
